# https://github.com/lsd-rs/lsd/blob/58a8723cfa699d426bc3933c8aca91ad19ffee25/README.md?plain=1#L25
[font.normal]
family = "FiraCode Nerd Font"

[keyboard]
bindings = [
    # https://github.com/alacritty/alacritty/issues/474#issuecomment-338803299
    { chars = "\u001BOH", key = "Left", mods = "Command" },
    { chars = "\u001BOF", key = "Right", mods = "Command" },
    { chars = "\u0015", key = "Back", mods = "Command" },
]
